name: CI

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Coding style (check)
        run: composer cs:check

      - name: PHPStan
        run: composer stan

      - name: PHPUnit
        run: composer test